services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", PG_DATABASE, "-U", PG_USER ]
      interval: 0.1s
      timeout: 10s
      retries: 5
      start_period: 80s
